
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("Validator")
export class Validator extends AbstractEntity  {

	@Required
	@Column("String")
	id: String

	@Required
	@Column("String")
	validatorPubKey: String

	@Required
	@Column("String")
	podOwner: String

	@Required
	@Column("String")
	eigenPod: String

	@Required
	@Column("Boolean")
	isRegistered: Boolean

	@Required
	@Column("Boolean")
	isPodDeployed: Boolean
  constructor(data: Partial<Validator>) {super()}
}


const source = `type Validator @entity {
  id: String!
  validatorPubKey: String!
  podOwner: String!
  eigenPod: String!
  isRegistered: Boolean!
  isPodDeployed: Boolean!
}`
DatabaseSchema.register({
  source,
  entities: {
    "Validator": Validator
  }
})
